spring:
  config:
    import:
      - optional:configserver:https://ecommerce-config-service.onrender.com/
      - optional:file:.env[.properties]
  application:
    name: order-service
  profiles:
    active:
      - dev

application:
  config:
    cron:
      expression: 0 */2 * * * *
      order-older-than: 5
